version: '3.4'

x-base: &x-base
  volumes:
  - .:$PWD
  - ~/.composer/cache:/composer-cache
  - ~/.composer/auth.json:/composer/auth.json
  working_dir: $PWD
  command: sshd

services:
  php:
    <<: *x-base
    image: "minidocks/php:${PHP_VERSION:-7.4}"

  php-tools:
    <<: *x-base
    image: "minidocks/php-tools:${PHP_VERSION:-7.4}"
